version: "3.4"
services:
  # unified database for host + gdps
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./_mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "GlooseDumbass"
      MARIADB_USER: "gen_user"
      MARIADB_PASSWORD: "pineappol"
  # keydb for gdps config storage (db 7)
  keydb:
    image: eqalpha/keydb:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./_keydb:/data
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./_minio:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "apache"
      MINIO_ROOT_PASSWORD: "apache2077"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  # ghostcore itself
  ghostcore:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - keydb
      - minio
    ports:
      - 80:1997
    environment:
      MASTER_KEY: "3XTR4OrD1nArY_K3Y_1907"
      DB_USER: "gen_user"
      DB_PASS: "pineappol"
      DB_HOST: "mariadb"
      REDIS_PORT: "6379"
      REDIS_HOST: "keydb"
      REDIS_PASSWORD: ""
      SAVE_PATH: "/core"
      S3_CONFIG: "access_key=apache,secret=apache2077,region=us-east-1,bucket=default,endpoint=minio,cdn=minio"
      CONSUL_ADDR: "consul:8500"
      CONSUL_DC: "dc1"