name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps:
#      - name: Notify xHydra
#        uses: nobrayner/discord-webhook@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          discord-webhook: https://discord.com/api/webhooks/998519688680177666/GQbhxOvtw2B06N5JCdnsOb30Rx2LFdh1bE-dHJUHQIQVbbSe0URZIWVnczesMJlGtKEp
#          username: 'Github Pipelines'
#          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
      - name: Notify HalHost
        uses: nobrayner/discord-webhook@v1
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           discord-webhook: https://discord.com/api/webhooks/1005819284301291572/qnyDf9_ZCiMVS7kPd6ovusqNB0T0P1McdrEs4oRv7VbPAygkK4LZodN7_5xV9nG3u2GC
           username: 'Github Pipelines'
           avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
