name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} cr.yandex

    - name: Build
      run: docker build -t cr.yandex/crpr24jcqm2dno6qlm3b/ghostcore

    - name: Push
      run: docker push cr.yandex/crpr24jcqm2dno6qlm3b/ghostcore

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps:
      - name: Notify Fruitspace
        uses: nobrayner/discord-webhook@v1
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           discord-webhook: https://discord.com/api/webhooks/1270366524128886815/2m_aquhXryYhMkw37KRLs6TqBh3D6gDI7Gs-Gio12ba3bLxvJ92Oej9qJnlyomvVH7_g
           username: 'Github Pipelines'
           avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
